os:
  - linux
language: node_js

node_js:
  - "node"

before_script:
    - npm run build:clean

script:
    - npm run lint
    - npm run test
    - npm run coverage

after_success:
    - npm install -g coveralls && npm run coverage:report | coveralls

jobs:
  include:
    - stage: "Deploy"
      deploy:
        provider: npm
        email: $NPM_EMAIL_ADDRESS
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
          branch: master

notifications:
  email:
    recipients:
    - caiodelgado.csd@gmail.com
    on_success: change
    on_failure: always
