language: node_js

node_js:
  - "node"

before_script:
    - npm run build

script:
    - npm run lint
    - npm run test
    - npm run coverage

after_success:
    - npm install -g coveralls && npm run coverage:report | coveralls

notifications:
  email:
    recipients:
    - caiodelgado.csd@gmail.com
    on_success: change
    on_failure: always
